### ISSUE TITLE
Faulty code example in LockedDataset docstring

### ISSUE THREAD

**Issue by RGrze** [piotrmaslanka/satella#49]
Code example in LockedDataset's docstring is faulty.

``` 
class LockedDataset:
    """
    A locked dataset. Subclass like

    >>> class MyDataset(LockedDataset):
    >>>     def __init__(self):
    >>>         super(MyDataset, self).__init__()
    >>>         self.mydata: str = "lol wut"
```

Setting `self.mydata` on init requires `with self:` clause. Otherwise it will raise ResourceNotLocked on object creation.

**Comment by piotrmaslanka** [comment]
Thank you, I'll fix it as soon as I get home.
